name: xmastree
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.0
  intl: ^0.17.0
  json_annotation: ^4.7.0
  shared_preferences: ^2.0.0
  sliver_tools: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.0
  flutter_lints: ^2.0.0
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
